spring.application.name=clipgrowth-backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

storage.local.path=./storage